config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
                  path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
                  path(
                      "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
                  ),
                  # Django Admin, use {% url 'admin:index' %}
                  path(settings.ADMIN_URL, admin.site.urls),
                  # User management
                  path("users/", include("htmx_tutorial.users.urls", namespace="users")),
                  path("clients/", include("htmx_tutorial.clients.urls", namespace="clients")),
                  path("accounts/", include("allauth.urls")),
                  # Your stuff: custom urls includes go here
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

htmx_tutorial/clients/urls.py
from django.urls import path

from .views import client_list_view, add_client, delete_client, search_client, clear, sort_clients

app_name = 'clients'

urlpatterns = [
    path('clients/', client_list_view, name='clients-list'),
    path('add-client/', add_client, name='add-client'),
    path('delete-client/<int:pk>/', delete_client, name='delete-client-x'),
    path('search-client/', search_client, name='search-client'),
    path('sort-client/', sort_clients, name='sort-client'),
    path('clear/', clear, name='clear-messages'),
    #Client CRUD urls
    path(r'client/list/', client_list_view, name='list-client'),
    path(r'client/create/', client_create_view, name='create-client'),
    path(r'client/update/<int:pk>/', client_update_view, name='update-client'),
    path(r'client/delete/<int:pk>/', client_delete_view, name='delete-client'),
    path(r'client/<int:pk>/', client_detail_view, name='detail-client'),

]

htmx_tutorial/users/urls.py
from django.urls import path

from htmx_tutorial.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

htmx_tutorial/clients/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

# Create your models here.
from django_extensions.db.models import TimeStampedModel
from django.conf import settings
from django.db import models


class AuditableModel(models.Model):
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, related_name="created_%(class)s", null=True, on_delete=models.SET_NULL
    )
    modified_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, related_name="modified_%(class)s", null=True, on_delete=models.SET_NULL
    )

    class Meta:
        abstract = True


class Client(AuditableModel, TimeStampedModel):
    name = models.CharField(_('Name'), max_length=120)
    national_id = models.CharField(_('National id'), max_length=80, unique=True)
    verification_digit = models.CharField(_('Verification  digit'), max_length=3, null=True, blank=True)
    metadata = models.JSONField(_('Metadata'), null=True, blank=True)
    is_active = models.BooleanField(_('Is active'), default=True)
    display_order = models.PositiveIntegerField(_('Display Order'), default=0)

    class Meta:
        ordering = ('display_order', 'name')

    def __str__(self):
        return self.name

htmx_tutorial/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """Default user for HTMX Tutorial."""

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

htmx_tutorial/clients/forms.py
from django import forms
from django.core.exceptions import ValidationError

from htmx_tutorial.clients.models import Client
from htmx_tutorial.clients.utils import get_max_order


class SimpleClientForm(forms.Form):
    input_text = forms.CharField()
    first_name = forms.CharField(required=False)
    last_name = forms.CharField(required=False)

    def clean(self):
        cleaned_data = super(SimpleClientForm, self).clean()
        input_text = cleaned_data['input_text'].title()
        if ',' in input_text:
            parts = input_text.split(',')
            if len(parts) == 2:
                cleaned_data['last_name'] = parts[0]
                cleaned_data['first_name'] = parts[1]
            else:
                msg = 'More than one comma'
                raise ValidationError(msg)
        else:
            parts = input_text.split(' ')
            if len(parts) < 2:
                msg = 'Need to include first and last name'
                raise ValidationError(msg)
            else:
                cleaned_data['last_name'] = parts[-1]
                cleaned_data['first_name'] = ' '.join(parts[:-1])
        return cleaned_data

    def save(self):
        data = self.cleaned_data
        if Client.objects.filter(first_name=data['first_name'], last_name=data['last_name']).exists():
            client = Client.objects.get(first_name=data['first_name'], last_name=data['last_name'])
            client.display_order = get_max_order()
            client.is_active = True
            client.save()
        else:
            client = Client.objects.create(first_name=data['first_name'], last_name=data['last_name'],
                                           display_order=get_max_order())
        # client, _ = Client.objects.get_or_create(first_name=data['first_name'], last_name=data['last_name'])
        # if not client.is_active:
        #     client.is_active = True
        #     client.save()
        return client

htmx_tutorial/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):
    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }

htmx_tutorial/clients/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import render
from django.utils.translation import ugettext_lazy as _
# Create your views here.
from django.views.decorators.http import require_http_methods
from django.views.generic import ListView

from .forms import SimpleClientForm
from .models import Client


@login_required
def add_client(request):
    client_name = request.POST.get('client-name')
    form = SimpleClientForm(data={'input_text': client_name})
    if form.is_valid():
        form.save()
    else:
        messages.error(request, _('Error parsing client name.'))

    context = {'clients': Client.objects.filter(is_active=True).all()}
    return render(request, 'partials/client-list.html', context)


@login_required
@require_http_methods(['DELETE'])
def delete_client(request, pk):
    Client.objects.filter(pk=pk).update(is_active=False, display_order=0)

    context = {'clients': Client.objects.filter(is_active=True).all()}
    return render(request, 'partials/client-list.html', context)


@login_required
@require_http_methods(['POST'])
def search_client(request):
    search_text = request.POST.get('search')
    results = Client.objects.filter(last_name__icontains=search_text, is_active=False)
    context = {'results': results}
    return render(request, 'partials/search-results.html', context)


@login_required
def clear(request):
    return HttpResponse('')


@login_required
@require_http_methods(['POST'])
def sort_clients(request):
    client_pks_order = request.POST.getlist('client_order')
    client_list = []
    for idx, client_pk in enumerate(client_pks_order, start=1):
        client = Client.objects.get(pk=client_pk)
        client.display_order = idx
        client.save()
        client_list.append(client)

    return render(request, 'partials/client-list.html', {'clients': client_list})


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('clients:list-client')


client_create_view = ClientCreateView.as_view()


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('clients:list-client')


client_update_view = ClientUpdateView.as_view()


class ClientListView(LoginRequiredMixin, ListView):
    model = Client
    context_object_name = 'client_list'
    paginate_by = 10


client_list_view = ClientListView.as_view()


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    model = Client
    success_url = reverse_lazy('clients:list-client')


client_delete_view = ClientDeleteView.as_view()


class ClientDetailView(LoginRequiredMixin, DetailView):
    model = Client


client_detail_view = ClientDetailView.as_view()

htmx_tutorial/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.request.user.id, int)
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False)
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

htmx_tutorial/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        return self.request.user.get_absolute_url()  # type: ignore [union-attr]

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

htmx_tutorial/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block title %}HTMX Tutorial{% endblock title %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="HTMX Tutorial">
  <meta name="author" content="Luis C. Berrocal">

  <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

  {% block css %}
    <!-- Latest compiled and minified Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/css/bootstrap.min.css"
          integrity="sha512-GQGU0fMMi238uA+a/bdWJfpUGKUkBdgfFdgBm72SUQ6BeyWjoY/ton0tEjH+OSH9iP4Dfh+7HM0I9f5eR0L/4w=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css">
    <!-- Your stuff: Third-party CSS libraries go here -->
    <!-- This file stores project-specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
  {% endblock %}
  <!-- Le javascript
  ================================================== -->
  {# Placed at the top of the document so pages load faster with defer #}
  {% block javascript %}
    <!-- Bootstrap JS -->
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/js/bootstrap.min.js"
            integrity="sha512-OvBgP9A2JBgiRad/mM36mkzXSXaJE9BEIENnVEmeZdITvwT09xnxLtT4twkCa8m/loMbPHsvPl0T8lRGVBwjlQ=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <!-- Your stuff: Third-party javascript libraries go here -->
    <script src="https://unpkg.com/htmx.org@1.6.0"></script>
    <!-- place project specific Javascript in this file -->
    <script src="https://cdn.jsdelivr.net/npm/sortablejs@latest/Sortable.min.js"></script>
    <script defer src="{% static 'js/project.js' %}"></script>

  {% endblock javascript %}

</head>

<body>

<div class="mb-1">
  <nav class="navbar navbar-expand-md navbar-light bg-light">
    <div class="container-fluid">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse"
              data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
              aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="{% url 'home' %}">HTMX Tutorial</a>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'home' %}">Home <span class="visually-hidden">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'about' %}">About</a>
          </li>
          {% if request.user.is_authenticated %}
            <li class="nav-item">
              {# URL provided by django-allauth/account/urls.py #}
              <a class="nav-link"
                 href="{% url 'users:detail' request.user.username %}">{% translate "My Profile" %}</a>
            </li>
            <li class="nav-item">
              {# URL provided by django-allauth/account/urls.py #}
              <a class="nav-link" href="{% url 'account_logout' %}">{% translate "Sign Out" %}</a>
            </li>
          {% else %}
            <li class="nav-item">
              {# URL provided by django-allauth/account/urls.py #}
              <a id="sign-up-link" class="nav-link"
                 href="{% url 'account_signup' %}">{% translate "Sign Up" %}</a>
            </li>
            <li class="nav-item">
              {# URL provided by django-allauth/account/urls.py #}
              <a id="log-in-link" class="nav-link"
                 href="{% url 'account_login' %}">{% translate "Sign In" %}</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

</div>

<div class="container">

  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-dismissible {% if message.tags %}alert-{{ message.tags }}{% endif %}">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% endfor %}
  {% endif %}

  {% block content %}
    <div class="container">
      <div class="row">
        <div class="col-6">
          <a class="btn btn-sm btn-primary" href="{% url 'clients:clients-list' %}">Clients</a>
        </div>
      </div>
      <div class="row">
        <div class="col">
          Based on tutorial from bugbites <a href="https://github.com/bugbytes-io/django-htmx">Github repo</a>
        </div>
      </div>
      <div class="row">
        <div class="col">
          Using bootstrap icons <a href="https://icons.getbootstrap.com/">Link</a>
        </div>
      </div>
    </div>
    </div>

  {% endblock content %}

</div> <!-- /container -->

{% block modal %}{% endblock modal %}

{% block inline_javascript %}
  {% comment %}
    Script tags with only code, no src (defer by default). To run
    with a "defer" so that you run run inline code:
    <script>
      window.addEventListener('DOMContentLoaded', () => {/* Run whatever you want */});
    </script>
    {% endcomment %}
{% endblock inline_javascript %}

<script>
  document.body.addEventListener('htmx:configRequest', (event) => {
    event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
  })
</script>
<script>
  htmx.onLoad(function (content) {
    var sortables = content.querySelectorAll(".sortable");
    for (var i = 0; i < sortables.length; i++) {
      var sortable = sortables[i];
      new Sortable(sortable, {
        animation: 150,
        ghostClass: 'blue-background-class'
      });
    }
  })
</script>
</body>
</html>